package java16;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class TestTryWithResourcesCatchJ16 {
   public void test(File var1) {
      try {
         try (Scanner var2 = new Scanner(var1)) {// 9
            var2.next();// 10
         }
      } catch (FileNotFoundException var7) {// 11
         var7.printStackTrace();// 12
      }

   }// 14

   public void testFunc(File var1) {
      try {
         try (Scanner var2 = this.create(var1)) {// 17
            var2.next();// 18
         }
      } catch (FileNotFoundException var7) {
         var7.printStackTrace();// 20
      }
   }// 22

   private Scanner create(File var1) throws FileNotFoundException {
      return new Scanner(var1);// 25
   }
}

class 'java16/TestTryWithResourcesCatchJ16' {
   method 'test (Ljava/io/File;)V' {
      4      9
      8      9
      9      10
      a      10
      b      10
      c      10
      2a      12
      2c      13
      2f      16
   }

   method 'testFunc (Ljava/io/File;)V' {
      0      20
      1      20
      2      20
      3      20
      4      20
      5      20
      6      21
      7      21
      8      21
      9      21
      31      24
      34      26
   }

   method 'create (Ljava/io/File;)Ljava/util/Scanner;' {
      4      29
      8      29
   }
}

Lines mapping:
9 <-> 10
10 <-> 11
11 <-> 13
12 <-> 14
14 <-> 17
17 <-> 21
18 <-> 22
20 <-> 25
22 <-> 27
25 <-> 30
Not mapped:
13
19
21
