package java16;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class TestTryWithResourcesCatchJ16 {
   public void test(File var1) {
      try {
         try (Scanner var2 = new Scanner(var1)) {// 9
            var2.next();// 10
         }

      } catch (FileNotFoundException var7) {// 11
         var7.printStackTrace();// 12
      }

   }// 14

   public void testFunc(File var1) {
      try {
         try (Scanner var2 = this.create(var1)) {// 17
            var2.next();// 18
         }
      } catch (FileNotFoundException var7) {
         var7.printStackTrace();// 20
      }
   }// 22

   private Scanner create(File var1) throws FileNotFoundException {
      return new Scanner(var1);// 25
   }
}

class 'java16/TestTryWithResourcesCatchJ16' {
   method 'test (Ljava/io/File;)V' {
      4      9
      8      9
      9      10
      a      10
      b      10
      c      10
      2a      13
      2c      14
      2f      17
   }

   method 'testFunc (Ljava/io/File;)V' {
      0      21
      1      21
      2      21
      3      21
      4      21
      5      21
      6      22
      7      22
      8      22
      9      22
      31      25
      34      27
   }

   method 'create (Ljava/io/File;)Ljava/util/Scanner;' {
      4      30
      8      30
   }
}

Lines mapping:
9 <-> 10
10 <-> 11
11 <-> 14
12 <-> 15
14 <-> 18
17 <-> 22
18 <-> 23
20 <-> 26
22 <-> 28
25 <-> 31
Not mapped:
13
19
21
